config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :my_orders, only: :index

  get 'about', to: 'pages#about'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :products, only: [:index, :show, :new] do
    member do
      post :add_to_cart
      delete :remove_from_cart
    end
  end

  resources :orders, only: [:show, :create] do
    resources :payments, only: :new
  end

  resources :shops, only: [:index, :show]
  resources :orders, only: [:show, :destroy, :update]

  get '/my_orders', to: 'my_orders#my_orders'
  mount StripeEvent::Engine, at: '/stripe-webhooks'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :order_product_relationships, dependent: :destroy
  has_many :products, through: :order_product_relationships

  monetize :amount_cents
end

app/models/order_product_relationship.rb
class OrderProductRelationship < ApplicationRecord
  belongs_to :order
  belongs_to :product
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :shop
  has_many :order_product_relationships
  has_one_attached :photo
  has_many :orders

  monetize :price_cents
  validates :name, presence: true
  # validates :description, presence: true
  # validates :price, presence: true
  # validates :quantity, presence: true
  # validates :supplier_country, presence: true
  # validates :categories, inclusion: { in: %w(Gluten free Dairy free Sugar free Vegan Vegetarian Pescetarian Organic) }
  # validates :calories, presence: true
  # validates :shop, presence: true

# CATEGORIES = ["Gluten free", "Dairy free", "Sugar free",
#               "Vegan", "Vegetarian", "Pescetarian", "Organic"]
# validates :categories, inclusion: { in: CATEGORIES }
end

app/models/shop.rb
class Shop < ApplicationRecord
  has_many :products, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :orders_as_owner, through: :orders, source: :orders

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
  has_many_attached :photos

  validates :name, presence: true, uniqueness: true
  # validates :phone_number, presence: true
  # validates :address, presence: true
  # validates :email, presence: true, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  has_many :orders, dependent: :destroy
  has_one_attached :photo

  # validates :first_name, presence: true
  # validates :last_name, presence: true
  # validates :phone_number, presence: true
  # validates :address, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  include Pundit

  # after_action :verify_authorized, except: :index, unless: :skip_pundit?
  # after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :phone_number, :address])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end

  private

  def skip_pundit?
    true
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/my_orders_controller.rb
class MyOrdersController < ApplicationController
  def index
    @orders = current_user.orders
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def create
    # 1) you fetch the products to be bought(cart)
    # 2) you calculate their sum value
    # 3) you create the order with state, user and amount
    # 4) you create the order_product_relationships
    products = session[:cart].map { |id| Product.find(id) }
    # products = Product.where(id: session[:cart])
    # @order.group(:product).count

    order = Order.new(
      state: 'pending',
      user: current_user,
      amount_cents: products.pluck(:price_cents).sum
    )

    products.each { |product| order.order_product_relationships.build(product: product) }
    order.save
    session = Stripe::Checkout::Session.create(
      line_items: products.map { |product| { name: product.name, quantity: 1, amount: product.price_cents, currency: 'aed' } },
      payment_method_types: ['card'],
      success_url: order_url(order),
      cancel_url: order_url(order)
    )

    if order.persisted?
      session[:cart] = []
      order.update(checkout_session_id: session.id)
      redirect_to order_path(order)
    end
  end

  def show
    @order = Order.find(params[:id])

    session[:cart] = [] if @order.state == 'completed'
    @basket = @order.products
                    .group_by { |product| product }
                    .transform_values{ |values| values.count }
    # binding.pry
  end

  def update
    @order = Order.find(params[:id])
    @order.update(state: 'completed')
    session[:cart] = []
    SmsNotificationJob.perform_later(@order.user)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  # skip_before_action :authenticate_user!, only: [ :home ]

  def home
    @products = Product.all
  end

  def about
  end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  def new
    @order = current_user.orders.where(state: 'pending').find(params[:order_id])
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  # skip_before_action :authenticate_user!, only: [:home, :index, :show, :add_to_cart, :remove_from_cart ]
  before_action :initialize_session
  before_action :increment_visit_count
  before_action :load_cart
  skip_before_action :verify_authenticity_token, if: :text_request?

  def index
    @products = Product.all

    if params[:category].present?
      @products = @products.where('?=ANY(categories)', params[:category])
    end

    if params[:query].present?
      sql_query = " \
         products.name ILIKE :query \
         OR products.description ILIKE :query \
         OR products.supplier_country ILIKE :query \
         OR shops.name ILIKE :query \
       "
      @products = Product.joins(:shop).where(sql_query, query: "%#{params[:query]}%")
    end

    respond_to do |format|
      format.html
      format.text { render partial: 'products/list', locals: { products: @products }, formats: [:html] }
    end
  end

  def show
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    @product.update(product_params)

    respond_to do |format|
      format.html { redirect_to products_path }
      format.text { render partial: 'products/product_infos', locals: { product: @product }, formats: [:html] }
    end
  end

  def add_to_cart
    id = params[:id].to_i
    # session[:cart] << id unless session[:cart].include?(id)
    session[:cart] << id
    p '-' * 10
    p session[:cart]
    p '-' * 10
    respond_to do |format|
      format.text { render partial: 'products/cart_info', locals: { product_id: id, cart: session[:cart] }, formats: [:html] }
    end
  end

  def remove_from_cart
    id = params[:id].to_i
    session[:cart].delete_at(session[:cart].index(id))
    respond_to do |format|
      format.text { render partial: 'products/cart_info', locals: { product_id: id, cart: session[:cart] }, formats: [:html] }
    end
  end

  private

  def product_params
    params.require(:product).permit(:name, :description, :price, :category, :quantity)
  end

  def initialize_session
    session[:visit_count] ||= 0 # Assign this value if nil.
    session[:cart] ||= [] # Empty cart is an empty array.
  end

  def increment_visit_count
    session[:visit_count] += 1
    @visit_count = session[:visit_count]
  end

  def load_cart
    @cart = session[:cart] || []
  end

  def text_request?
    request.format.text?
  end
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  def index
    @shops = Shop.all

    @markers = @shops.geocoded.map do |shop|
      {
        lat: shop.latitude,
        lng: shop.longitude,
      }
    end
  end

  def show
    @shop = Shop.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Veggielite</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <%= stylesheet_pack_tag 'application' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <div class="min-vh-100">
      <%= yield %>
    </div>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/my_orders/_form.html.erb
<%= render "form" %>
<%= render :partial => 'form', locals: { post: @post } %>
<div class="col-sm-3">
    <div class="card" style="width: 18rem;">
      <div class="card-body">
        <h5 class="card-title">Special title treatment</h5>
        <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
        <a href="#" class="btn btn-primary">Go somewhere</a>
      </div>
    </div>
  </div>

app/views/my_orders/_order.html.erb
<div class="container">
  <%# TABS  %>

  <%# End of TABS %>
  <html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Bootstrap Utility Classes</title>
    <link rel="shortcut icon" href="data:image/x-icon;" type="image/x-icon">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css">
  </head>
  <body class="bg-light">

    <!-- navbar -->
    <div class="border-bottom bg-white">
      <div class="container d-flex align-items-center justify-content-between py-2">
        <img src="images/deliveroo.png" alt="" width="140px">
      </div>
    </div>
    <!-- /navbar -->
    <% order.products.each do |product| %>
      <%= product.name %>
    <% end %>

    <!-- restaurant info -->
    <div class="bg-white">
      <div class="container p-3">
        <div class="row">
          <div class="col-md-8">
            <h3>Holist Union</h3>
            <p>An all-day Healthy Food Bar - serving authentic  whole foods</p>
          </div>
          <div class="col-md-4">
            <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTVociO7PJK-EOOVz1f-se7zT6euNErCJTcXA&usqp=CAU" alt="" class="w-100">
          </div>
        </div>
      </div>
    </div>
    <!-- /restaurant info -->

    <!-- restaurant menu / checkout-->
    <div class="container py-3">
      <div class="row">
        <div class="col-md-8">

          <!-- turn this into an alert (warning) -->
          <div class="alert alert-warning" role="alert">
            Going to order for same day delivery? You'll need to order before 12pm. <strong>ID</strong>.
          </div>

          <h2>Your Groceries</h2>

          <!-- make a card -->
          <div class="card p-3 mb-3">
            <p class=""><strong>@product.name</strong></p>
            <p class=""><small>@product.description</small></p>
            <span class="">@product.price</span>
          </div>

        <div class="col-md-4">
          <!-- checkout -->
          <div class="bg-white border p-3 sticky-top">
            <a href="#" class="btn btn-primary w-100">Checkout</a>

            <div class="d-flex justify-content-between mt-3">
              <p><strong>Quinoa</strong> (1)</p>
              <p>£4.95</p>
            </div>

            <div class="d-flex justify-content-between mt-3">
              <p><strong>Granola</strong> (2)</p>
              <p>£11.90</p>
            </div>

            <div class="d-flex justify-content-between mt-3 border-bottom">
              <p><strong>Greek yoghurt</strong> (1)</p>
              <p>£6.95</p>
            </div>

            <div class="d-flex justify-content-between mt-3">
              <p><strong>Total</strong></p>
              <p><strong>£23.80</strong></p>
            </div>
          </div>
          <!-- /checkout -->
        </div>
      </div>
    </div>

    <!-- Including Bootstrap JS (with its Popper.js / jQuery dependency) so that dynamic components work -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
  </body>
</html>

app/views/my_orders/index.html.erb
<div class="container">
  <%# TABS  %>
  <ul class="nav nav-tabs" id="myTab" role="tablist">
    <li class="nav-item" role="presentation">
      <a class="nav-link active" id="past-tab" data-toggle="tab" href="#past" role="tab" aria-controls="past" aria-selected="true">Past Orders</a>
    </li>
    <li class="nav-item" role="presentation">
      <a class="nav-link" id="current-tab" data-toggle="tab" href="#current" role="tab" aria-controls="current" aria-selected="false">Current Orders</a>
    </li>
  </ul>
  <%# End of TABS %>
</div>

<% @orders.each do |order| %>
  <%= render partial: "order", locals: { order: order } %>
<% end %>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Bootstrap Utility Classes</title>
    <link rel="shortcut icon" href="data:image/x-icon;" type="image/x-icon">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css">
  </head>
  <body class="bg-light">

    <!-- navbar -->
    <div class="border-bottom bg-white">
      <div class="container d-flex align-items-center justify-content-between py-2">
        <img src="images/deliveroo.png" alt="" width="140px">

        <!-- turn this link into a button -->
        <a href="#" class="">Update</a>
      </div>
    </div>
    <!-- /navbar -->

    <!-- restaurant info -->
    <div class="bg-white">
      <div class="container p-3">
        <div class="row">
          <div class="col-md-8">
            <h3>Your Dashboard</h3>
            <p></p>
          </div>
          <div class="col-md-4">
            <img src="https://f.roocdn.com/images/menus/70997/header-image.jpg?width=740&height=320&auto=webp&format=jpg&fit=crop&v=1531393618" alt="" class="w-100">
          </div>
        </div>
      </div>
    </div>
    <!-- /restaurant info -->

    <!-- restaurant menu / checkout-->
    <div class="container py-3">
      <div class="row">
        <div class="col-md-8">

          <!-- turn this into an alert (warning) -->
          <div class="alert alert-warning" role="alert">
            Turn on notifications for delivered groceries <strong>.</strong>.
          </div>

          <h2>Your Customers</h2>

          <!-- make a card -->
          <div class="card p-3 mb-3">
            <p class=""><strong>Marjorie Johnson</strong></p>
            <p class=""><small>Tomato</small></p>
            <p class=""><small>Spinach</small></p>
            <p class=""><small>Cheese</small></p>
            <span class="">£5.95</span>
          </div>

          <!-- make a card -->
          <div class="card p-3 mb-3">
            <p class=""><strong>Diavola Stewart</strong></p>
            <p class=""><small>Lettuce</small></p>
            <p class=""><small>Onion</small></p>

            <span class="">£5.95</span>
          </div>

          <!-- make a card -->
          <div class="card p-3 mb-3">
            <p class=""><strong>Regina Sofianopoulis</strong></p>
            <p class=""><small>Tomato
            <p class=""><small>Lettuce</small></p>

            </small></p>
            <span class="">£5.95</span>
          </div>

          <!-- make a card -->
          <div class="card p-3 mb-3">
            <p class=""><strong>George Townsend</strong></p>
            <p class=""><small>Sourdough</small></p>
            <p class=""><small>Greek yoghurt</small></p>
            <p class=""><small></small></p>

            <span class="">£5.95</span>
          </div>

          <!-- make a card -->
          <div class="card p-3 mb-3">
            <p class=""><strong>Tristan Thompson</strong></p>
            <p class=""><small>Basil</small></p>
            <p class=""><small>Cheese</small></p>
            <span class="">£5.95</span>
          </div>
          <!-- /menu -->
        </div>

        <div class="col-md-4">
          <!-- checkout -->
          <div class="bg-white border p-3 sticky-top">
            <a href="#" class="btn btn-primary w-100">Delivery Locations</a>

            <div class="d-flex justify-content-between mt-3">
              <p><strong>Dubai</strong> (1)</p>
              <p>£4.95</p>
            </div>

            <div class="d-flex justify-content-between mt-3">
              <p><strong>Sharjah</strong> (2)</p>
              <p>£11.90</p>
            </div>

            <div class="d-flex justify-content-between mt-3 border-bottom">
              <p><strong>Abu Dhabi</strong> (1)</p>
              <p>£6.95</p>
            </div>

            <div class="d-flex justify-content-between mt-3">
              <p><strong>Total</strong></p>
              <p><strong>£23.80</strong></p>
            </div>
          </div>
          <!-- /checkout -->
        </div>
      </div>
    </div>

    <!-- Including Bootstrap JS (with its Popper.js / jQuery dependency) so that dynamic components work -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
  </body>
</html>

app/views/orders/_form.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1572357176061-7c96fd2af22f?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=3735&q=80);">
  <<h1>VEGGIELITE</h1>
  <p>Convenient and seamless grocery shopping experience!</p>
</div>
<div class="container">
  <div class="row justify-content-center">
    <div class="col-6">
      <%= simple_form_for(@product) do |r| %>
        <%= r.error_notification %>
        <%= r.error_notification message: r.object.errors[:base].to_sentence if r.object.errors[:base].present? %>

        <div class="form-inputs">
          <%= r.input :name %>
          <%= r.input :description %>
          <%= r.input :categories, collection: Product::CATEGORIES %>
          <%= r.input :price %>
          <%= r.input :photos, as: :file, input_html: { multiple: true } %>
        </div>

        <div class="form-actions">
          <%= r.button :submit, class: "btn btn-success" %>
          <%= link_to 'Back', root_path, class: "btn btn-secondary my-3" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/payments/new.html.erb
<div class="container">
  <div class="row py-4">
    <% @order.products.each do |product| %>
      <div class="col">
        <h1>Checkout summary</h1>
        <p>Purchase of <strong><%= product.name %></strong> for
          <strong><%= humanized_money_with_symbol product.price %></strong>
          <%= render partial: 'cart_info', locals: { product_id: product.id, cart: @cart } %>
        </p>

      </div>


    <% end %>

  </div>
</div>

app/views/products/_cart_info.html.erb
<div data-controller="cart" data-cart-target="links" data-basket="<%= session[:cart].to_json %>" data-product=" <%= product_id %> ">

  <div class="quantity d-flex">

     <div class="minus"> <%= link_to '-', remove_from_cart_product_path(product_id), method: :delete, data: { action: 'click->cart#removeProduct', cart_target: "remove", index: "product-#{product_id}" }, class: 'cart-minus' %> </div>

      <span class="cart-number" id="product-<%= product_id %>">0</span>


      <div class="plus"><%= link_to '+', add_to_cart_product_path(product_id), method: :post, data: { action: 'click->cart#addProduct', cart_target: "add", index: "product-#{product_id}" }, class: 'cart-plus' %> </div>

  </div>
</div>

app/views/products/_list.html.erb
  <div data-search-products-target="list" class="home-container">
    <p class="products-count-indicator" style="padding:14px; border-radius:4px; background-color:white; font-weight:500; color:#5ba368;">
      <% if params[:query].blank? %>
        <%= pluralize products.count, 'product' %> available
      <% else %>
        <%= pluralize products.count, 'result' %> for <code><%= params[:query] %></code>
      <% end %>
    </p>
    <div class="products">
      <%# <% products.each do |product| %>
        <%= render partial: 'product_infos', locals: { products: products, cart: @cart } %>
      <%# <% end %>
    </div>
  </div>

app/views/products/_product_infos.html.erb
<div class=" position absolute">
  <div class="row">
    <div class="col">
      <div class="mproduct-card">
        <div class="cards">
          <% products.each do |product| %>
            <div class="card">
          <div class="card-trip position relative">
            <div class="card-img"><%= cl_image_tag product.photo.key %></div>
            <div class="card-infos d-flex">
              <div style="width: 60%;">
                <%= link_to product.name, product, class: 'product-name' %>

                <div style="border-left: 0.2rem solid var(--clr-green-300); padding-left: 1rem;">
                  <p class="products-calories"> <strong>Calories:</strong> <%= product.calories %> </p>
                  <p> Protein: <%= product.macros['protein'] %> </p>
                  <p> Fat: <%= product.macros['fat'] %> </p>
                  <p> Carbs: <%= product.macros['carbs'] %> </p>
                </div>
              </div>
              <div style="width: 40%; text-align: right;">
                <h2 class="product-price"><%= humanized_money_with_symbol(product.price) %></h2>
                  <%= render partial: 'cart_info', locals: { product_id: product.id, cart: @cart }%>
              </div>
            </div>
          </div>

        </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_footer.html.erb
<!-- Footer -->
<footer class="page-footer font-small indigo">

  <!-- Footer Links -->
  <div class="container">

    <!-- Grid row-->
    <div class="row text-center d-flex justify-content-center pt-5 mb-3">

      <!-- Grid column -->
      <div class="col-md-2 mb-3">

        <h6 class="text-uppercase font-weight-bold text-green">
          <%= link_to "About us", about_path %>
        </h6>
      </div>

      <!-- Grid column -->
      <div class="col-md-2 mb-3">

        <h6 class="text-uppercase font-weight-bold text-green">
          <%= link_to "Our Healthy Products", shops_path %>
        </h6>
      </div>

      <!-- Grid column -->
      <div class="col-md-2 mb-3">

        <h6 class="text-uppercase font-weight-bold text-green">
          <a href="#!">Our Partners</a>
        </h6>
      </div>
      <!-- Grid column -->

      <!-- Grid column -->
      <div class="col-md-2 mb-3">

        <h6 class="text-uppercase font-weight-bold text-green">
          <a href="#!">Contact</a>
        </h6>

      <!-- Grid column -->
    </div>
  </div>
    <!-- Grid row-->
    <hr class="rgba-white-light" style="margin: 0 15%;">

    <!-- Grid row-->
    <div class="row d-flex text-center justify-content-center mb-md-0 mb-4">

      <!-- Grid column -->
      <div class="col-md-8 col-12 mt-5">
        <p style="line-height: 1.7rem">We know it can be a struggle to get quality ingredients that suit your dietary needs in Dubai! This is why our team here at Veggielite is committed to keeping you fresh and fruity to conquer the day!</p>
      </div>
      <!-- Grid column -->

    </div>
    <!-- Grid row-->
    <hr class="clearfix d-md-none rgba-white-light" style="margin: 10% 15% 5%;">

    <!-- Grid row-->
    <div class="row">

      <!-- Grid column -->
      <div class="col-md-12">

        <div class="mb-3 mt-3 flex-center">
          <div class="center-text">
            <!-- Facebook -->
            <a href="https://www.facebook.com/Veggielite-Store-102674858920029" class="icons m-3">
              <i class="fab fa-facebook-f fa-lg white-text mr-4"></i>
            </a>
            <!-- Twitter -->
            <a href="https://www.instagram.com/veggielite_/" class="icons m-3">
              <i class="fab fa-twitter fa-lg white-text mr-4"> </i>
            </a>

            <!--Instagram-->
            <a href="https://www.instagram.com/veggielite_/" class="icons m-3">
              <i class="fab fa-instagram fa-lg white-text mr-4"> </i>
            </a>
          </div>
        </div>

      </div>
      <!-- Grid column -->

    </div>
    <!-- Grid row-->

  </div>
  <!-- Footer Links -->

  <!-- Copyright -->
  <div class="footer-copyright text-center pb-3 text-green">© 2021 Copyright: Stay fresh and fruity!
  </div>
  <!-- Copyright -->

</footer>
<!-- Footer -->

app/views/shared/_navbar.html.erb
<div class="bg-white sticky">
  <div class="nav home-container sticky">

    <%= link_to root_path, class: "logo" do %>
      <%= image_tag "veggielite_logo.png" %>
    <% end %>

    <ul class="nav-buttons">
      <li><%= link_to "Home", root_path, class:"btn-home" %></li>
      <li><% if current_user && @cart %>
          <%= button_to orders_path, disabled: true do %>
            <div class="btn-checkout" data-bs-toggle="tooltip" data-placement="left" title="Checkout">
              <i class="fas fa-shopping-cart" style='font-size:17px;'>
                <span class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-warning" style="16px;" id="counter">
                  <%= @cart.size %>
                </span>
              </i>
            </div>
          <% end %>
          <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog">
              <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-title" id="exampleModalLabel">Cart</h5>
                  <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                  Here goes the product list
                </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                  <%= button_to 'Checkout', orders_path %>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      </li>
      <%# <li><%= link_to "Log In", new_user_session_path, class: 'btn-login'</li> %>
      <li class="nav-item dropdown">
        <%= link_to new_user_session_path do %>
          <i class="fas fa-user-circle" style='font-size:33px; color: var(--clr-green-300);'></i>
        <% end %>

        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <%= link_to "Sign Up", new_user_registration_path, class: "dropdown-item" %>
          <%= link_to "Log In", new_user_session_path, class: "dropdown-item" %>
          <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
        </div>
      </li>
    </ul>
  </div>
</div>